# Generated by Django 3.2.25 on 2024-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_game',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
