# Generated by Django 3.2.25 on 2024-03-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.CharField(max_length=250),
        ),
    ]
