# Generated by Django 3.2.25 on 2024-03-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saved', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('strategy', 'Strategy'), ('card_game', 'Card Game'), ('casual', 'Casual'), ('quiz', 'Quiz'), ('deck_building', 'Deck Building'), ('cooperative', 'Cooperative'), ('party', 'Party'), ('puzzle', 'Puzzle'), ('adventure', 'Adventure'), ('role_playing', 'Role Playing'), ('simulation', 'Simulation'), ('trivia', 'Trivia'), ('other', 'Other')], default='strategy', max_length=40),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='review_connect',
            field=models.ManyToManyField(blank=True, to='saved.Save'),
        ),
    ]
